"$schema" = 'https://starship.rs/config-schema.json'

format = "$os -> $username -> $directory $line_break$character"
right_format = "$git_branch$git_status $python $conda"

palette = 'gruvbox_hard'
[palettes.gruvbox_hard]
color_fg0 = '#fbf1c7'
color_bg1 = '#1d2021'
color_bg3 = '#3c3836'
color_blue = '#83a598'
color_aqua = '#8ec07c'
color_green = '#b8bb26'
color_orange = '#fe8019'
color_purple = '#d3869b'
color_red = '#fb4934'
color_yellow = '#fabd2f'

[character]
success_symbol = '[->](fg:color_green)'
error_symbol = '[->](fg:color_red)'
vimcmd_symbol = '[->](fg:color_purple)'

[os]
disabled = false
style = "bold fg:color_orange"
format = "[$symbol]($style)"
[os.symbols]
Macos = "󰀵"
Linux = "󰌽"
Windows = "󰍲"

[username]
show_always = true
style_user = "bold fg:color_orange"
format = "[$user]($style)"

[directory]
format = '[$path]($style)'
style = "bold fg:color_blue"
truncation_length = 5
truncation_symbol = "…/"

[git_branch]
symbol = ""
format = '[$symbol $branch]($style)'
style = "fg:color_aqua"

[git_status]
format = '([$all_status]($style))'
style = "fg:color_purple"

[conda]
format = '[$environment]($style)'
style = "fg:color_yellow"
ignore_base = true

[python]
format = '[py $version]($style)'
style = "fg:color_yellow"

